# Form implementation generated from reading ui file 'add_courses_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCourseDialog(object):
    def setupUi(self, AddCourseDialog):
        AddCourseDialog.setObjectName("AddCourseDialog")
        AddCourseDialog.resize(505, 444)
        AddCourseDialog.setMinimumSize(QtCore.QSize(0, 0))
        AddCourseDialog.setMaximumSize(QtCore.QSize(780, 580))
        AddCourseDialog.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(AddCourseDialog)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.headerFrame = QtWidgets.QFrame(parent=AddCourseDialog)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.headerFrame.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f093fb, stop:1 #f5576c); border-radius: 0px;")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setObjectName("headerFrame")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.headerLayout.setContentsMargins(30, 20, 30, 20)
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.labelTitle.setStyleSheet("font-size: 24px; font-weight: bold; color: white; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.buttonClose = QtWidgets.QPushButton(parent=self.headerFrame)
        self.buttonClose.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonClose.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonClose.setStyleSheet("QPushButton { background-color: rgba(255,255,255,0.2); color: white; border: none; border-radius: 20px; font-size: 18px; font-weight: bold; } QPushButton:hover { background-color: rgba(255,255,255,0.3); }")
        self.buttonClose.setObjectName("buttonClose")
        self.headerLayout.addWidget(self.buttonClose)
        self.mainLayout.addWidget(self.headerFrame)
        self.scrollArea = QtWidgets.QScrollArea(parent=AddCourseDialog)
        self.scrollArea.setStyleSheet("border: none; background-color: #f5f7fa;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 505, 284))
        self.scrollContent.setStyleSheet("background-color: #f5f7fa;")
        self.scrollContent.setObjectName("scrollContent")
        self.contentLayout = QtWidgets.QVBoxLayout(self.scrollContent)
        self.contentLayout.setContentsMargins(30, 30, 30, 30)
        self.contentLayout.setSpacing(20)
        self.contentLayout.setObjectName("contentLayout")
        self.formGrid = QtWidgets.QGridLayout()
        self.formGrid.setHorizontalSpacing(20)
        self.formGrid.setVerticalSpacing(15)
        self.formGrid.setObjectName("formGrid")
        self.pushButton = QtWidgets.QPushButton(parent=self.scrollContent)
        self.pushButton.setObjectName("pushButton")
        self.formGrid.addWidget(self.pushButton, 10, 2, 1, 1)
        self.lineEditCourseCode = QtWidgets.QLineEdit(parent=self.scrollContent)
        self.lineEditCourseCode.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditCourseCode.setStyleSheet("padding: 10px 15px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 14px; background-color: white;")
        self.lineEditCourseCode.setObjectName("lineEditCourseCode")
        self.formGrid.addWidget(self.lineEditCourseCode, 1, 0, 1, 1)
        self.lineEditCourseName = QtWidgets.QLineEdit(parent=self.scrollContent)
        self.lineEditCourseName.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditCourseName.setStyleSheet("padding: 10px 15px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 14px; background-color: white;")
        self.lineEditCourseName.setObjectName("lineEditCourseName")
        self.formGrid.addWidget(self.lineEditCourseName, 1, 2, 1, 1)
        self.labelCourseName = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelCourseName.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelCourseName.setObjectName("labelCourseName")
        self.formGrid.addWidget(self.labelCourseName, 0, 2, 1, 1)
        self.labelCourseCode = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelCourseCode.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelCourseCode.setObjectName("labelCourseCode")
        self.formGrid.addWidget(self.labelCourseCode, 0, 0, 1, 1)
        self.labelCreditHours = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelCreditHours.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelCreditHours.setObjectName("labelCreditHours")
        self.formGrid.addWidget(self.labelCreditHours, 2, 0, 1, 1)
        self.lineEditCreditHours = QtWidgets.QLineEdit(parent=self.scrollContent)
        self.lineEditCreditHours.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditCreditHours.setStyleSheet("padding: 10px 15px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 14px; background-color: white;")
        self.lineEditCreditHours.setObjectName("lineEditCreditHours")
        self.formGrid.addWidget(self.lineEditCreditHours, 10, 0, 1, 1)
        self.contentLayout.addLayout(self.formGrid)
        spacerItem1 = QtWidgets.QSpacerItem(17, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.contentLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollContent)
        self.mainLayout.addWidget(self.scrollArea)
        self.footerFrame = QtWidgets.QFrame(parent=AddCourseDialog)
        self.footerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.footerFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.footerFrame.setStyleSheet("background-color: white; border-top: 2px solid #e0e0e0;")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setObjectName("footerFrame")
        self.footerLayout = QtWidgets.QHBoxLayout(self.footerFrame)
        self.footerLayout.setContentsMargins(30, 20, 30, 20)
        self.footerLayout.setObjectName("footerLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem2)
        self.buttonCancel = QtWidgets.QPushButton(parent=self.footerFrame)
        self.buttonCancel.setMinimumSize(QtCore.QSize(120, 45))
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    color: #5a6c7d;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* darker grey for pressed feedback */\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")
        self.footerLayout.addWidget(self.buttonCancel)
        self.buttonSave = QtWidgets.QPushButton(parent=self.footerFrame)
        self.buttonSave.setMinimumSize(QtCore.QSize(120, 45))
        self.buttonSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonSave.setStyleSheet("QPushButton {\n"
"    background-color: #f5576c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    transition: background-color 150ms;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e5475c;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d43f52;\n"
"}\n"
"")
        self.buttonSave.setObjectName("buttonSave")
        self.footerLayout.addWidget(self.buttonSave)
        self.mainLayout.addWidget(self.footerFrame)

        self.retranslateUi(AddCourseDialog)
        QtCore.QMetaObject.connectSlotsByName(AddCourseDialog)

    def retranslateUi(self, AddCourseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCourseDialog.setWindowTitle(_translate("AddCourseDialog", "Add New Course"))
        self.labelTitle.setText(_translate("AddCourseDialog", "📚  Add New Course"))
        self.buttonClose.setText(_translate("AddCourseDialog", "✕"))
        self.pushButton.setText(_translate("AddCourseDialog", "PushButton"))
        self.lineEditCourseCode.setPlaceholderText(_translate("AddCourseDialog", "e.g., ECE 101"))
        self.lineEditCourseName.setPlaceholderText(_translate("AddCourseDialog", "e.g., Digital Logic Design"))
        self.labelCourseName.setText(_translate("AddCourseDialog", "Course Name *"))
        self.labelCourseCode.setText(_translate("AddCourseDialog", "Course Code *"))
        self.labelCreditHours.setText(_translate("AddCourseDialog", "Credit Hours *"))
        self.lineEditCreditHours.setPlaceholderText(_translate("AddCourseDialog", "e.g., Dr. John Smith"))
        self.buttonCancel.setText(_translate("AddCourseDialog", "Cancel"))
        self.buttonSave.setText(_translate("AddCourseDialog", "💾  Save Course"))
