# Form implementation generated from reading ui file 'all_students.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AllStudents(object):
    def setupUi(self, AllStudents):
        AllStudents.setObjectName("AllStudents")
        AllStudents.resize(1200, 1069)
        AllStudents.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(AllStudents)
        self.mainLayout.setContentsMargins(40, 40, 40, 20)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=AllStudents)
        self.labelTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.labelTotalStudentsCount = QtWidgets.QLabel(parent=AllStudents)
        self.labelTotalStudentsCount.setStyleSheet("font-size: 16px;\n"
"color: #1a73e8;               /* blue text for emphasis */\n"
"font-weight: bold;\n"
"background-color: #e8f0fe;    /* light blue background */\n"
"padding: 8px 20px;\n"
"border-radius: 20px;\n"
"")
        self.labelTotalStudentsCount.setObjectName("labelTotalStudentsCount")
        self.headerLayout.addWidget(self.labelTotalStudentsCount)
        self.mainLayout.addLayout(self.headerLayout)
        self.filterFrame = QtWidgets.QFrame(parent=AllStudents)
        self.filterFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.filterFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.filterFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.filterFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.filterFrame.setObjectName("filterFrame")
        self.filterLayout = QtWidgets.QHBoxLayout(self.filterFrame)
        self.filterLayout.setContentsMargins(25, 15, 25, 15)
        self.filterLayout.setObjectName("filterLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.filterFrame)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;   /* light neutral background */\n"
"    color: #5a6c7d;             /* text color similar to buttons */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #f5576c;       /* accent border on focus */\n"
"    background-color: #ffffff;   /* slightly lighter when active */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #ededed;   /* washed-out grey */\n"
"    color: #a1a8b3;             /* faded text */\n"
"}\n"
"")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.filterLayout.addWidget(self.lineEditSearch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem1)
        self.buttonRefresh = QtWidgets.QPushButton(parent=self.filterFrame)
        self.buttonRefresh.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonRefresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRefresh.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    color: #5a6c7d;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* darker grey for pressed feedback */\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}")
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.filterLayout.addWidget(self.buttonRefresh)
        self.mainLayout.addWidget(self.filterFrame)
        self.tableFrame = QtWidgets.QFrame(parent=AllStudents)
        self.tableFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.tableMainLayout = QtWidgets.QVBoxLayout(self.tableFrame)
        self.tableMainLayout.setContentsMargins(0, 0, 0, 0)
        self.tableMainLayout.setSpacing(0)
        self.tableMainLayout.setObjectName("tableMainLayout")
        self.tableHeader = QtWidgets.QFrame(parent=self.tableFrame)
        self.tableHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.tableHeader.setMaximumSize(QtCore.QSize(16777215, 60))
        self.tableHeader.setStyleSheet("background: transparent; border-bottom: 2px solid #f0f0f0;")
        self.tableHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableHeader.setObjectName("tableHeader")
        self.tableHeaderLayout = QtWidgets.QHBoxLayout(self.tableHeader)
        self.tableHeaderLayout.setContentsMargins(25, 15, 25, 15)
        self.tableHeaderLayout.setObjectName("tableHeaderLayout")
        self.tableTitle = QtWidgets.QLabel(parent=self.tableHeader)
        self.tableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.tableTitle.setObjectName("tableTitle")
        self.tableHeaderLayout.addWidget(self.tableTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tableHeaderLayout.addItem(spacerItem2)
        self.buttonAddStudent = QtWidgets.QPushButton(parent=self.tableHeader)
        self.buttonAddStudent.setEnabled(False)
        self.buttonAddStudent.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonAddStudent.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonAddStudent.setStyleSheet("/* ---- Approve Button ---- */\n"
"QPushButton {\n"
"    background-color: #d4edda;\n"
"    color: #155724;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;  /* slightly darker for pressed feedback */\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #c1d9c3; /* more washed-out green */\n"
"    color: #7a8b7a;\n"
"}")
        self.buttonAddStudent.setObjectName("buttonAddStudent")
        self.tableHeaderLayout.addWidget(self.buttonAddStudent)
        self.buttonRemoveSelected = QtWidgets.QPushButton(parent=self.tableHeader)
        self.buttonRemoveSelected.setEnabled(False)
        self.buttonRemoveSelected.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonRemoveSelected.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRemoveSelected.setStyleSheet("/* ---- Reject Button ---- */\n"
"QPushButton {\n"
"    background-color: #f8d7da;\n"
"    color: #721c24;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a71d2a;  /* slightly darker for pressed feedback */\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7bcbc; /* more washed-out red */\n"
"    color: #5e3b3e;\n"
"}")
        self.buttonRemoveSelected.setObjectName("buttonRemoveSelected")
        self.tableHeaderLayout.addWidget(self.buttonRemoveSelected)
        self.tableMainLayout.addWidget(self.tableHeader)
        self.mainLayout.addWidget(self.tableFrame)
        self.tableAllStudents = QtWidgets.QTableWidget(parent=AllStudents)
        self.tableAllStudents.setMinimumSize(QtCore.QSize(0, 300))
        self.tableAllStudents.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #e5e5e5;      /* slightly darker for visibility */\n"
"    color: #222222;               /* matches QLineEdit text color */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 14px;\n"
"    border: none;\n"
"    color: #222222;               /* consistent text color */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #fcebed;  /* soft pink selection */\n"
"    color: #222222;             /* keep text readable */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 12px;\n"
"    border: 1px solid #c1c1c1; \n"
"    font-size: 13px;\n"
"    color: #555555;               /* similar to readOnly QLineEdit text */\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"/* Removes weird selection rectangle */\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"QTableWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QTableWidget::indicator:unchecked {\n"
"    border: 1px solid #b8b8b8;      /* soft grey border */\n"
"    background-color: #f8f8f8;      /* very light grey */\n"
"    border-radius: 3px;             /* slightly rounded */\n"
"}\n"
"\n"
"QTableWidget::indicator:checked {\n"
"    border: 1px solid #5a5a5a;      /* darker grey when selected */\n"
"    background-color: #6c6c6c;      /* washed-out grey instead of harsh green */\n"
"    image: url(\"\");                 /* remove default checkmark */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked:hover,\n"
"QTableWidget::indicator:unchecked:hover {\n"
"    border-color: #3a3a3a;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked::after {\n"
"    content: \"\";\n"
"    image: url(\"\"); /* no default checkmark */\n"
"}")
        self.tableAllStudents.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableAllStudents.setAlternatingRowColors(True)
        self.tableAllStudents.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableAllStudents.setCornerButtonEnabled(True)
        self.tableAllStudents.setObjectName("tableAllStudents")
        self.tableAllStudents.setColumnCount(8)
        self.tableAllStudents.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllStudents.setHorizontalHeaderItem(7, item)
        self.tableAllStudents.horizontalHeader().setStretchLastSection(True)
        self.tableAllStudents.verticalHeader().setVisible(False)
        self.tableAllStudents.verticalHeader().setCascadingSectionResizes(True)
        self.mainLayout.addWidget(self.tableAllStudents)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem3)

        self.retranslateUi(AllStudents)
        QtCore.QMetaObject.connectSlotsByName(AllStudents)

    def retranslateUi(self, AllStudents):
        _translate = QtCore.QCoreApplication.translate
        AllStudents.setWindowTitle(_translate("AllStudents", "Pending Requests"))
        self.labelTitle.setText(_translate("AllStudents", "All Students"))
        self.labelTotalStudentsCount.setText(_translate("AllStudents", "200 Total Students"))
        self.lineEditSearch.setPlaceholderText(_translate("AllStudents", "🔍  Search by student name or ID..."))
        self.buttonRefresh.setText(_translate("AllStudents", "🔄 Refresh"))
        self.tableTitle.setText(_translate("AllStudents", "Registered Students"))
        self.buttonAddStudent.setText(_translate("AllStudents", "➕ Add New Student (WIP)"))
        self.buttonRemoveSelected.setText(_translate("AllStudents", "❌ Remove Selected"))
        item = self.tableAllStudents.horizontalHeaderItem(0)
        item.setText(_translate("AllStudents", "SELECT"))
        item = self.tableAllStudents.horizontalHeaderItem(1)
        item.setText(_translate("AllStudents", "#"))
        item = self.tableAllStudents.horizontalHeaderItem(2)
        item.setText(_translate("AllStudents", "ID"))
        item = self.tableAllStudents.horizontalHeaderItem(3)
        item.setText(_translate("AllStudents", "NAME"))
        item = self.tableAllStudents.horizontalHeaderItem(4)
        item.setText(_translate("AllStudents", "EMAIL"))
        item = self.tableAllStudents.horizontalHeaderItem(5)
        item.setText(_translate("AllStudents", "PROGRAM"))
        item = self.tableAllStudents.horizontalHeaderItem(6)
        item.setText(_translate("AllStudents", "STATE"))
        item = self.tableAllStudents.horizontalHeaderItem(7)
        item.setText(_translate("AllStudents", "ACTION"))
