# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverviewWidget(object):
    def setupUi(self, OverviewWidget):
        OverviewWidget.setObjectName("OverviewWidget")
        OverviewWidget.resize(863, 819)
        OverviewWidget.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(OverviewWidget)
        self.mainLayout.setContentsMargins(40, 40, 40, 40)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(parent=OverviewWidget)
        self.titleLabel.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(20)
        self.statsLayout.setObjectName("statsLayout")
        self.totalUsersFrame = QtWidgets.QFrame(parent=OverviewWidget)
        self.totalUsersFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.totalUsersFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #667eea;")
        self.totalUsersFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.totalUsersFrame.setObjectName("totalUsersFrame")
        self.totalUsersLayout = QtWidgets.QVBoxLayout(self.totalUsersFrame)
        self.totalUsersLayout.setContentsMargins(24, 24, 24, 24)
        self.totalUsersLayout.setSpacing(12)
        self.totalUsersLayout.setObjectName("totalUsersLayout")
        self.totalUsersIcon = QtWidgets.QLabel(parent=self.totalUsersFrame)
        self.totalUsersIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.totalUsersIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.totalUsersIcon.setStyleSheet("background-color: #e8eaf6; border-radius: 10px; font-size: 24px;")
        self.totalUsersIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalUsersIcon.setObjectName("totalUsersIcon")
        self.totalUsersLayout.addWidget(self.totalUsersIcon)
        self.totalUsersValue = QtWidgets.QLabel(parent=self.totalUsersFrame)
        self.totalUsersValue.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.totalUsersValue.setObjectName("totalUsersValue")
        self.totalUsersLayout.addWidget(self.totalUsersValue)
        self.totalUsersLabel = QtWidgets.QLabel(parent=self.totalUsersFrame)
        self.totalUsersLabel.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.totalUsersLabel.setObjectName("totalUsersLabel")
        self.totalUsersLayout.addWidget(self.totalUsersLabel)
        self.statsLayout.addWidget(self.totalUsersFrame)
        self.pendingRequestsFrame_2 = QtWidgets.QFrame(parent=OverviewWidget)
        self.pendingRequestsFrame_2.setMinimumSize(QtCore.QSize(0, 160))
        self.pendingRequestsFrame_2.setStyleSheet("background-color: white;\n"
"border-radius: 12px;\n"
"border-top: 4px solid #f5576c;  /* same color as Edit Profile button */\n"
"")
        self.pendingRequestsFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pendingRequestsFrame_2.setObjectName("pendingRequestsFrame_2")
        self.pendingRequestsLayout_2 = QtWidgets.QVBoxLayout(self.pendingRequestsFrame_2)
        self.pendingRequestsLayout_2.setContentsMargins(24, 24, 24, 24)
        self.pendingRequestsLayout_2.setSpacing(12)
        self.pendingRequestsLayout_2.setObjectName("pendingRequestsLayout_2")
        self.pendingRequestsIcon_2 = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.pendingRequestsIcon_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon_2.setStyleSheet("background-color: #fff3e0; border-radius: 10px; font-size: 24px;")
        self.pendingRequestsIcon_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pendingRequestsIcon_2.setObjectName("pendingRequestsIcon_2")
        self.pendingRequestsLayout_2.addWidget(self.pendingRequestsIcon_2)
        self.pendingRequestsValue_2 = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.pendingRequestsValue_2.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.pendingRequestsValue_2.setObjectName("pendingRequestsValue_2")
        self.pendingRequestsLayout_2.addWidget(self.pendingRequestsValue_2)
        self.pendingRequestsLabel_2 = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.pendingRequestsLabel_2.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.pendingRequestsLabel_2.setObjectName("pendingRequestsLabel_2")
        self.pendingRequestsLayout_2.addWidget(self.pendingRequestsLabel_2)
        self.statsLayout.addWidget(self.pendingRequestsFrame_2)
        self.totalStudentsFrame = QtWidgets.QFrame(parent=OverviewWidget)
        self.totalStudentsFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.totalStudentsFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #f093fb;")
        self.totalStudentsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.totalStudentsFrame.setObjectName("totalStudentsFrame")
        self.totalStudentsLayout = QtWidgets.QVBoxLayout(self.totalStudentsFrame)
        self.totalStudentsLayout.setContentsMargins(24, 24, 24, 24)
        self.totalStudentsLayout.setSpacing(12)
        self.totalStudentsLayout.setObjectName("totalStudentsLayout")
        self.totalStudentsIcon = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.totalStudentsIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.totalStudentsIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.totalStudentsIcon.setStyleSheet("background-color: #fce4ec; border-radius: 10px; font-size: 24px;")
        self.totalStudentsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalStudentsIcon.setObjectName("totalStudentsIcon")
        self.totalStudentsLayout.addWidget(self.totalStudentsIcon)
        self.totalStudentsValue = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.totalStudentsValue.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.totalStudentsValue.setObjectName("totalStudentsValue")
        self.totalStudentsLayout.addWidget(self.totalStudentsValue)
        self.totalStudentsLabel = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.totalStudentsLabel.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.totalStudentsLabel.setObjectName("totalStudentsLabel")
        self.totalStudentsLayout.addWidget(self.totalStudentsLabel)
        self.statsLayout.addWidget(self.totalStudentsFrame)
        self.pendingRequestsFrame = QtWidgets.QFrame(parent=OverviewWidget)
        self.pendingRequestsFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.pendingRequestsFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #ffa647;")
        self.pendingRequestsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pendingRequestsFrame.setObjectName("pendingRequestsFrame")
        self.pendingRequestsLayout = QtWidgets.QVBoxLayout(self.pendingRequestsFrame)
        self.pendingRequestsLayout.setContentsMargins(24, 24, 24, 24)
        self.pendingRequestsLayout.setSpacing(12)
        self.pendingRequestsLayout.setObjectName("pendingRequestsLayout")
        self.pendingRequestsIcon = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.pendingRequestsIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon.setStyleSheet("background-color: #fff3e0; border-radius: 10px; font-size: 24px;")
        self.pendingRequestsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pendingRequestsIcon.setObjectName("pendingRequestsIcon")
        self.pendingRequestsLayout.addWidget(self.pendingRequestsIcon)
        self.pendingRequestsValue = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.pendingRequestsValue.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.pendingRequestsValue.setObjectName("pendingRequestsValue")
        self.pendingRequestsLayout.addWidget(self.pendingRequestsValue)
        self.pendingRequestsLabel = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.pendingRequestsLabel.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.pendingRequestsLabel.setObjectName("pendingRequestsLabel")
        self.pendingRequestsLayout.addWidget(self.pendingRequestsLabel)
        self.statsLayout.addWidget(self.pendingRequestsFrame)
        self.mainLayout.addLayout(self.statsLayout)
        self.adminInfoFrame = QtWidgets.QFrame(parent=OverviewWidget)
        self.adminInfoFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.adminInfoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.adminInfoFrame.setObjectName("adminInfoFrame")
        self.adminInfoMainLayout = QtWidgets.QVBoxLayout(self.adminInfoFrame)
        self.adminInfoMainLayout.setContentsMargins(0, 0, 0, 0)
        self.adminInfoMainLayout.setSpacing(0)
        self.adminInfoMainLayout.setObjectName("adminInfoMainLayout")
        self.adminInfoHeader = QtWidgets.QFrame(parent=self.adminInfoFrame)
        self.adminInfoHeader.setMinimumSize(QtCore.QSize(0, 70))
        self.adminInfoHeader.setMaximumSize(QtCore.QSize(16777215, 70))
        self.adminInfoHeader.setStyleSheet("background: transparent; border-bottom: 2px solid #f0f0f0;")
        self.adminInfoHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.adminInfoHeader.setObjectName("adminInfoHeader")
        self.adminInfoHeaderLayout = QtWidgets.QHBoxLayout(self.adminInfoHeader)
        self.adminInfoHeaderLayout.setContentsMargins(30, 20, 30, 20)
        self.adminInfoHeaderLayout.setObjectName("adminInfoHeaderLayout")
        self.adminInfoTitle = QtWidgets.QLabel(parent=self.adminInfoHeader)
        self.adminInfoTitle.setStyleSheet("font-size: 20px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.adminInfoTitle.setObjectName("adminInfoTitle")
        self.adminInfoHeaderLayout.addWidget(self.adminInfoTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.adminInfoHeaderLayout.addItem(spacerItem)
        self.buttonEdit = QtWidgets.QPushButton(parent=self.adminInfoHeader)
        self.buttonEdit.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonEdit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonEdit.setStyleSheet("QPushButton {\n"
"    background-color: #f5576c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    transition: background-color 150ms;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e5475c;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d43f52;\n"
"}\n"
"")
        self.buttonEdit.setObjectName("buttonEdit")
        self.adminInfoHeaderLayout.addWidget(self.buttonEdit)
        self.adminInfoMainLayout.addWidget(self.adminInfoHeader)
        self.adminInfoBody = QtWidgets.QWidget(parent=self.adminInfoFrame)
        self.adminInfoBody.setStyleSheet("background: transparent;")
        self.adminInfoBody.setObjectName("adminInfoBody")
        self.adminInfoBodyLayout = QtWidgets.QVBoxLayout(self.adminInfoBody)
        self.adminInfoBodyLayout.setContentsMargins(30, 30, 30, 30)
        self.adminInfoBodyLayout.setSpacing(20)
        self.adminInfoBodyLayout.setObjectName("adminInfoBodyLayout")
        self.fieldsGrid = QtWidgets.QGridLayout()
        self.fieldsGrid.setSpacing(20)
        self.fieldsGrid.setObjectName("fieldsGrid")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditPhone.setEnabled(True)
        self.lineEditPhone.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditPhone.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditPhone.setReadOnly(True)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.fieldsGrid.addWidget(self.lineEditPhone, 3, 0, 1, 1)
        self.labelEmail = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelEmail.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelEmail.setObjectName("labelEmail")
        self.fieldsGrid.addWidget(self.labelEmail, 0, 1, 1, 1)
        self.labelUsername = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelUsername.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelUsername.setObjectName("labelUsername")
        self.fieldsGrid.addWidget(self.labelUsername, 0, 0, 1, 1)
        self.lineEditDepartment = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditDepartment.setEnabled(True)
        self.lineEditDepartment.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditDepartment.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditDepartment.setReadOnly(True)
        self.lineEditDepartment.setObjectName("lineEditDepartment")
        self.fieldsGrid.addWidget(self.lineEditDepartment, 3, 1, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditName.setEnabled(True)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditName.setReadOnly(True)
        self.lineEditName.setObjectName("lineEditName")
        self.fieldsGrid.addWidget(self.lineEditName, 1, 0, 1, 1)
        self.labelDepatment = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelDepatment.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelDepatment.setObjectName("labelDepatment")
        self.fieldsGrid.addWidget(self.labelDepatment, 2, 1, 1, 1)
        self.lineEditPhone_2 = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditPhone_2.setEnabled(True)
        self.lineEditPhone_2.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditPhone_2.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditPhone_2.setReadOnly(True)
        self.lineEditPhone_2.setObjectName("lineEditPhone_2")
        self.fieldsGrid.addWidget(self.lineEditPhone_2, 5, 0, 1, 1)
        self.labelPhone = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelPhone.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelPhone.setObjectName("labelPhone")
        self.fieldsGrid.addWidget(self.labelPhone, 2, 0, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditEmail.setEnabled(True)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditEmail.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditEmail.setReadOnly(True)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.fieldsGrid.addWidget(self.lineEditEmail, 1, 1, 1, 1)
        self.labelPhone_2 = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelPhone_2.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelPhone_2.setObjectName("labelPhone_2")
        self.fieldsGrid.addWidget(self.labelPhone_2, 4, 0, 1, 1)
        self.adminInfoBodyLayout.addLayout(self.fieldsGrid)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem1)
        self.buttonCancel = QtWidgets.QPushButton(parent=self.adminInfoBody)
        self.buttonCancel.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    color: #5a6c7d;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* darker grey for pressed feedback */\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")
        self.buttonsLayout.addWidget(self.buttonCancel)
        self.buttonSave = QtWidgets.QPushButton(parent=self.adminInfoBody)
        self.buttonSave.setEnabled(False)
        self.buttonSave.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonSave.setStyleSheet("QPushButton {\n"
"    background-color: #f5576c;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e5475c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d93f53; /* slightly darker for click feedback */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #e0e0e0;\n"
"    color: #999999;\n"
"}\n"
"")
        self.buttonSave.setObjectName("buttonSave")
        self.buttonsLayout.addWidget(self.buttonSave)
        self.adminInfoBodyLayout.addLayout(self.buttonsLayout)
        self.adminInfoMainLayout.addWidget(self.adminInfoBody)
        self.mainLayout.addWidget(self.adminInfoFrame)

        self.retranslateUi(OverviewWidget)
        QtCore.QMetaObject.connectSlotsByName(OverviewWidget)

    def retranslateUi(self, OverviewWidget):
        _translate = QtCore.QCoreApplication.translate
        OverviewWidget.setWindowTitle(_translate("OverviewWidget", "Overview"))
        self.titleLabel.setText(_translate("OverviewWidget", "Profile Overview"))
        self.totalUsersIcon.setText(_translate("OverviewWidget", "👥"))
        self.totalUsersValue.setText(_translate("OverviewWidget", "1,245"))
        self.totalUsersLabel.setText(_translate("OverviewWidget", "Total Users"))
        self.pendingRequestsIcon_2.setText(_translate("OverviewWidget", "📔"))
        self.pendingRequestsValue_2.setText(_translate("OverviewWidget", "15"))
        self.pendingRequestsLabel_2.setText(_translate("OverviewWidget", "Total Faculty"))
        self.totalStudentsIcon.setText(_translate("OverviewWidget", "⚡"))
        self.totalStudentsValue.setText(_translate("OverviewWidget", "184"))
        self.totalStudentsLabel.setText(_translate("OverviewWidget", "Total Students"))
        self.pendingRequestsIcon.setText(_translate("OverviewWidget", "⏳"))
        self.pendingRequestsValue.setText(_translate("OverviewWidget", "12"))
        self.pendingRequestsLabel.setText(_translate("OverviewWidget", "Pending Requests"))
        self.adminInfoTitle.setText(_translate("OverviewWidget", "Admin Information"))
        self.buttonEdit.setText(_translate("OverviewWidget", "Edit Profile"))
        self.lineEditPhone.setText(_translate("OverviewWidget", "+966 508471281"))
        self.labelEmail.setText(_translate("OverviewWidget", "Email Address"))
        self.labelUsername.setText(_translate("OverviewWidget", "Username"))
        self.lineEditDepartment.setText(_translate("OverviewWidget", "Electrical and Computer Engineering"))
        self.lineEditName.setText(_translate("OverviewWidget", "admin_user"))
        self.labelDepatment.setText(_translate("OverviewWidget", "Department"))
        self.lineEditPhone_2.setText(_translate("OverviewWidget", "[HIDDEN]"))
        self.labelPhone.setText(_translate("OverviewWidget", "Phone Number"))
        self.lineEditEmail.setText(_translate("OverviewWidget", "admin@university.edu"))
        self.labelPhone_2.setText(_translate("OverviewWidget", "Password"))
        self.buttonCancel.setText(_translate("OverviewWidget", "Cancel"))
        self.buttonSave.setText(_translate("OverviewWidget", "Save Changes"))
