# Form implementation generated from reading ui file 'admin_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminDashboard(object):
    def setupUi(self, AdminDashboard):
        AdminDashboard.setObjectName("AdminDashboard")
        AdminDashboard.resize(1200, 835)
        AdminDashboard.setMinimumSize(QtCore.QSize(1200, 700))
        AdminDashboard.setStyleSheet("QMainWindow { background-color: #f5f7fa; }")
        self.centralwidget = QtWidgets.QWidget(parent=AdminDashboard)
        self.centralwidget.setStyleSheet("background-color: #f5f7fa;")
        self.centralwidget.setObjectName("centralwidget")
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainHorizontalLayout.setSpacing(0)
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.sidebarFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebarFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.sidebarFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sidebarFrame.setStyleSheet("QFrame { background-color: white; }")
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.sidebarLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarLayout.setSpacing(0)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.headerWidget = QtWidgets.QWidget(parent=self.sidebarFrame)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 210))
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.headerWidget.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f093fb, stop:1 #f5576c);")
        self.headerWidget.setObjectName("headerWidget")
        self.headerLayout = QtWidgets.QVBoxLayout(self.headerWidget)
        self.headerLayout.setContentsMargins(25, 32, 25, 28)
        self.headerLayout.setSpacing(20)
        self.headerLayout.setObjectName("headerLayout")
        self.logoHLayout = QtWidgets.QHBoxLayout()
        self.logoHLayout.setObjectName("logoHLayout")
        self.logoIconLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.logoIconLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.logoIconLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.logoIconLabel.setStyleSheet("background-color: white; border-radius: 15px; font-size: 34px;")
        self.logoIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIconLabel.setObjectName("logoIconLabel")
        self.logoHLayout.addWidget(self.logoIconLabel)
        self.logoTextLayout = QtWidgets.QVBoxLayout()
        self.logoTextLayout.setSpacing(4)
        self.logoTextLayout.setObjectName("logoTextLayout")
        self.logoTitleLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.logoTitleLabel.setStyleSheet("color: white; font-size: 23px; font-weight: 800; background: transparent;")
        self.logoTitleLabel.setObjectName("logoTitleLabel")
        self.logoTextLayout.addWidget(self.logoTitleLabel)
        self.logoSubtitleLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.logoSubtitleLabel.setStyleSheet("color: rgba(255,255,255,0.95); font-size: 13px; background: transparent;")
        self.logoSubtitleLabel.setObjectName("logoSubtitleLabel")
        self.logoTextLayout.addWidget(self.logoSubtitleLabel)
        self.logoHLayout.addLayout(self.logoTextLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoHLayout.addItem(spacerItem)
        self.headerLayout.addLayout(self.logoHLayout)
        self.profileFrame = QtWidgets.QFrame(parent=self.headerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileFrame.sizePolicy().hasHeightForWidth())
        self.profileFrame.setSizePolicy(sizePolicy)
        self.profileFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.profileFrame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255,255,255,0.22);\n"
"    border-radius: 15px;\n"
"    border: 1px solid rgba(255,255,255,0.35);\n"
"}")
        self.profileFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profileFrame.setObjectName("profileFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.profileFrame)
        self.gridLayout.setContentsMargins(-1, 5, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAdminName = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelAdminName.setMinimumSize(QtCore.QSize(20, 20))
        self.labelAdminName.setStyleSheet("color: white; \n"
"font-size: 17px; \n"
"font-weight: 800;\n"
"background: transparent;\n"
"border: transparent")
        self.labelAdminName.setObjectName("labelAdminName")
        self.verticalLayout.addWidget(self.labelAdminName)
        self.adminRole = QtWidgets.QLabel(parent=self.profileFrame)
        self.adminRole.setMinimumSize(QtCore.QSize(0, 20))
        self.adminRole.setStyleSheet("color: rgba(255,255,255,0.88); \n"
"font-size: 13px; \n"
"font-weight: 500;\n"
"background: transparent;\n"
"border: transparent")
        self.adminRole.setObjectName("adminRole")
        self.verticalLayout.addWidget(self.adminRole)
        self.adminStatus = QtWidgets.QLabel(parent=self.profileFrame)
        self.adminStatus.setMinimumSize(QtCore.QSize(0, 20))
        self.adminStatus.setStyleSheet("color: rgba(255,255,255,0.95); \n"
"font-size: 11px; \n"
"font-weight: 600;\n"
"border: transparent;\n"
"background-color: transparent")
        self.adminStatus.setObjectName("adminStatus")
        self.verticalLayout.addWidget(self.adminStatus)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.avatarLabel = QtWidgets.QLabel(parent=self.profileFrame)
        self.avatarLabel.setMinimumSize(QtCore.QSize(60, 60))
        self.avatarLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.avatarLabel.setStyleSheet("background-color: white;\n"
"color: #f5576c;\n"
"border-radius: 30px;\n"
"font-size: 26px;\n"
"font-weight: 900;")
        self.avatarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.avatarLabel.setObjectName("avatarLabel")
        self.gridLayout.addWidget(self.avatarLabel, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.headerLayout.addWidget(self.profileFrame)
        self.sidebarLayout.addWidget(self.headerWidget)
        self.navScrollArea = QtWidgets.QScrollArea(parent=self.sidebarFrame)
        self.navScrollArea.setStyleSheet("QScrollArea { background-color: white; border: none; }\n"
"\n"
"/* ----------------- Modern Scrollbar with Embedded SVG Arrows ----------------- */\n"
"/* Colors you can tweak */\n"
"@declared-track: #eef3fa;    /* track background */\n"
"@declared-handle: #c7ccd1;   /* handle normal */\n"
"@declared-handle-hover: #b6bcc2;\n"
"@declared-handle-pressed: #9fa7b0;\n"
"@declared-arrow-color: #7c8691;\n"
"@declared-size: 12px;\n"
"\n"
"/* ---------- Vertical scrollbar ---------- */\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: @declared-size;\n"
"    margin: 12px 0 12px 0; /* space for arrows */\n"
"}\n"
"\n"
"/* track (page area) */\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* handle */\n"
"QScrollBar::handle:vertical {\n"
"    background: @declared-handle;\n"
"    min-height: 28px;\n"
"    border-radius: 6px;\n"
"    margin: 2px 2px; /* keep small gap from edges */\n"
"}\n"
"QScrollBar::handle:vertical:hover { background: @declared-handle-hover; }\n"
"QScrollBar::handle:vertical:pressed { background: @declared-handle-pressed; }\n"
"\n"
"/* arrows - sizes set to match the scrollbar width */\n"
"QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"    height: 12px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* keep area clickable and subtly highlight on hover */\n"
"QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background: rgba(0,0,0,0.03);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* ---------- Horizontal scrollbar ---------- */\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: @declared-size;\n"
"    margin: 0 12px 0 12px;\n"
"}\n"
"QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: @declared-handle;\n"
"    min-width: 28px;\n"
"    border-radius: 6px;\n"
"    margin: 2px 2px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover { background: @declared-handle-hover; }\n"
"QScrollBar::handle:horizontal:pressed { background: @declared-handle-pressed; }\n"
"\n"
"/* arrows for horizontal */\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal {\n"
"    width: 12px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: left;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover,\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    background: rgba(0,0,0,0.03);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* ----------------- CUSTOM SVG ARROWS (embedded) -----------------\n"
"   We use small inline SVGs encoded as UTF-8 (URL-escaped).\n"
"   Change @declared-arrow-color if you want different arrow color.\n"
"   ---------------------------------------------------------------------------- */\n"
"\n"
"/* up arrow (vertical sub-line) */\n"
"QScrollBar::sub-line:vertical {\n"
"    image: url(\"data:image/svg+xml;utf8,\\\n"
"    <svg xmlns=\'http://www.w3.org/2000/svg\' width=\'10\' height=\'10\' viewBox=\'0 0 10 10\'>\\\n"
"    <polygon points=\'5,2 9,8 1,8\' fill=\'%237c8691\'/>\\\n"
"    </svg>\");\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* down arrow (vertical add-line) */\n"
"QScrollBar::add-line:vertical {\n"
"    image: url(\"data:image/svg+xml;utf8,\\\n"
"    <svg xmlns=\'http://www.w3.org/2000/svg\' width=\'10\' height=\'10\' viewBox=\'0 0 10 10\'>\\\n"
"    <polygon points=\'1,2 9,2 5,8\' fill=\'%237c8691\'/>\\\n"
"    </svg>\");\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* left arrow (horizontal sub-line) */\n"
"QScrollBar::sub-line:horizontal {\n"
"    image: url(\"data:image/svg+xml;utf8,\\\n"
"    <svg xmlns=\'http://www.w3.org/2000/svg\' width=\'10\' height=\'10\' viewBox=\'0 0 10 10\'>\\\n"
"    <polygon points=\'8,1 8,9 2,5\' fill=\'%237c8691\'/>\\\n"
"    </svg>\");\n"
"}\n"
"\n"
"/* right arrow (horizontal add-line) */\n"
"QScrollBar::add-line:horizontal {\n"
"    image: url(\"data:image/svg+xml;utf8,\\\n"
"    <svg xmlns=\'http://www.w3.org/2000/svg\' width=\'10\' height=\'10\' viewBox=\'0 0 10 10\'>\\\n"
"    <polygon points=\'2,1 8,5 2,9\' fill=\'%237c8691\'/>\\\n"
"    </svg>\");\n"
"}\n"
"\n"
"/* ----------------- Optional: make arrows a bit brighter on hover ----------------- */\n"
"QScrollBar::sub-line:vertical:hover image,\n"
"QScrollBar::add-line:vertical:hover image,\n"
"QScrollBar::sub-line:horizontal:hover image,\n"
"QScrollBar::add-line:horizontal:hover image {\n"
"    /* re-specify with a slightly darker color */\n"
"    image: url(\"data:image/svg+xml;utf8,\\\n"
"    <svg xmlns=\'http://www.w3.org/2000/svg\' width=\'10\' height=\'10\' viewBox=\'0 0 10 10\'>\\\n"
"    <polygon points=\'5,2 9,8 1,8\' fill=\'%236a7480\'/>\\\n"
"    </svg>\");\n"
"}")
        self.navScrollArea.setWidgetResizable(True)
        self.navScrollArea.setObjectName("navScrollArea")
        self.navScrollContent = QtWidgets.QWidget()
        self.navScrollContent.setGeometry(QtCore.QRect(0, -96, 286, 719))
        self.navScrollContent.setStyleSheet("background-color: white;")
        self.navScrollContent.setObjectName("navScrollContent")
        self.navMainLayout = QtWidgets.QVBoxLayout(self.navScrollContent)
        self.navMainLayout.setContentsMargins(20, 28, 20, 28)
        self.navMainLayout.setSpacing(28)
        self.navMainLayout.setObjectName("navMainLayout")
        self.dashboardSectionLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.dashboardSectionLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.dashboardSectionLabel.setObjectName("dashboardSectionLabel")
        self.navMainLayout.addWidget(self.dashboardSectionLabel)
        self.buttonProfile = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonProfile.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonProfile.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonProfile.setCheckable(True)
        self.buttonProfile.setObjectName("buttonProfile")
        self.buttonGroupSubmenus = QtWidgets.QButtonGroup(AdminDashboard)
        self.buttonGroupSubmenus.setObjectName("buttonGroupSubmenus")
        self.buttonGroupSubmenus.addButton(self.buttonProfile)
        self.navMainLayout.addWidget(self.buttonProfile)
        self.userMgmtLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.userMgmtLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.userMgmtLabel.setObjectName("userMgmtLabel")
        self.navMainLayout.addWidget(self.userMgmtLabel)
        self.buttonAllStudents = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonAllStudents.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonAllStudents.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonAllStudents.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonAllStudents.setCheckable(True)
        self.buttonAllStudents.setObjectName("buttonAllStudents")
        self.buttonGroupSubmenus.addButton(self.buttonAllStudents)
        self.navMainLayout.addWidget(self.buttonAllStudents)
        self.buttonApproveStudents = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonApproveStudents.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonApproveStudents.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonApproveStudents.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonApproveStudents.setCheckable(True)
        self.buttonApproveStudents.setObjectName("buttonApproveStudents")
        self.buttonGroupSubmenus.addButton(self.buttonApproveStudents)
        self.navMainLayout.addWidget(self.buttonApproveStudents)
        self.buttonManageFaculty = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageFaculty.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageFaculty.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageFaculty.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonManageFaculty.setCheckable(True)
        self.buttonManageFaculty.setObjectName("buttonManageFaculty")
        self.buttonGroupSubmenus.addButton(self.buttonManageFaculty)
        self.navMainLayout.addWidget(self.buttonManageFaculty)
        self.courseMgmtLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.courseMgmtLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.courseMgmtLabel.setObjectName("courseMgmtLabel")
        self.navMainLayout.addWidget(self.courseMgmtLabel)
        self.buttonManageCourses = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageCourses.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageCourses.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageCourses.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonManageCourses.setCheckable(True)
        self.buttonManageCourses.setObjectName("buttonManageCourses")
        self.buttonGroupSubmenus.addButton(self.buttonManageCourses)
        self.navMainLayout.addWidget(self.buttonManageCourses)
        self.buttonManageSections = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageSections.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageSections.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageSections.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonManageSections.setCheckable(True)
        self.buttonManageSections.setObjectName("buttonManageSections")
        self.buttonGroupSubmenus.addButton(self.buttonManageSections)
        self.navMainLayout.addWidget(self.buttonManageSections)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.navMainLayout.addItem(spacerItem3)
        self.buttonLogout = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonLogout.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonLogout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonLogout.setStyleSheet("QPushButton {\n"
"    background-color: #fff5f5;\n"
"    border: 2px solid #fed7d7;\n"
"    border-radius: 12px;\n"
"    color: #e53e3e;\n"
"    font-weight: 700;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 18px;\n"
"    /* Add subtle shadow for depth */\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton:hover {\n"
"    background-color: #fed7d7;\n"
"}\n"
"\n"
"/* Pressed effect */\n"
"QPushButton:pressed {\n"
"    background-color: #fbb6b6; /* slightly darker */\n"
"    padding-left: 20px;        /* move text slightly right to simulate press */\n"
"    padding-top: 2px;          /* move text slightly down */\n"
"    border-color: #f56565;     /* darker border */\n"
"}\n"
"")
        self.buttonLogout.setObjectName("buttonLogout")
        self.navMainLayout.addWidget(self.buttonLogout)
        self.navScrollArea.setWidget(self.navScrollContent)
        self.sidebarLayout.addWidget(self.navScrollArea)
        self.mainHorizontalLayout.addWidget(self.sidebarFrame)
        self.mainContentWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainContentWidget.setStyleSheet("background-color: #f5f7fa;")
        self.mainContentWidget.setObjectName("mainContentWidget")
        self.mainContentLayout = QtWidgets.QVBoxLayout(self.mainContentWidget)
        self.mainContentLayout.setContentsMargins(0, 0, 0, 0)
        self.mainContentLayout.setSpacing(0)
        self.mainContentLayout.setObjectName("mainContentLayout")
        self.topBarFrame = QtWidgets.QFrame(parent=self.mainContentWidget)
        self.topBarFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.topBarFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.topBarFrame.setStyleSheet("background-color: white;")
        self.topBarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topBarFrame.setObjectName("topBarFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.topBarFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pageTitleLabel = QtWidgets.QLabel(parent=self.topBarFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTitleLabel.sizePolicy().hasHeightForWidth())
        self.pageTitleLabel.setSizePolicy(sizePolicy)
        self.pageTitleLabel.setMinimumSize(QtCore.QSize(300, 30))
        self.pageTitleLabel.setStyleSheet("font-size: 30px; font-weight: 900; color: #1a202c; background: transparent;")
        self.pageTitleLabel.setObjectName("pageTitleLabel")
        self.verticalLayout_2.addWidget(self.pageTitleLabel)
        self.breadcrumbLabel = QtWidgets.QLabel(parent=self.topBarFrame)
        self.breadcrumbLabel.setStyleSheet("font-size: 14px; color: #718096; background: transparent;")
        self.breadcrumbLabel.setObjectName("breadcrumbLabel")
        self.verticalLayout_2.addWidget(self.breadcrumbLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.btnSettings = QtWidgets.QPushButton(parent=self.topBarFrame)
        self.btnSettings.setMinimumSize(QtCore.QSize(48, 48))
        self.btnSettings.setMaximumSize(QtCore.QSize(48, 48))
        self.btnSettings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSettings.setStyleSheet("QPushButton { background-color: #f8f9fa; border: none; border-radius: 12px; font-size: 20px; } QPushButton:hover { background-color: #e8ecf1; }")
        self.btnSettings.setObjectName("btnSettings")
        self.gridLayout_2.addWidget(self.btnSettings, 0, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 1, 1)
        self.btnNotifications = QtWidgets.QPushButton(parent=self.topBarFrame)
        self.btnNotifications.setMinimumSize(QtCore.QSize(48, 48))
        self.btnNotifications.setMaximumSize(QtCore.QSize(48, 48))
        self.btnNotifications.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNotifications.setStyleSheet("QPushButton { background-color: #f8f9fa; border: none; border-radius: 12px; font-size: 20px; } QPushButton:hover { background-color: #e8ecf1; }")
        self.btnNotifications.setObjectName("btnNotifications")
        self.gridLayout_2.addWidget(self.btnNotifications, 0, 5, 1, 1)
        self.btnMessages = QtWidgets.QPushButton(parent=self.topBarFrame)
        self.btnMessages.setMinimumSize(QtCore.QSize(48, 48))
        self.btnMessages.setMaximumSize(QtCore.QSize(48, 48))
        self.btnMessages.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMessages.setStyleSheet("QPushButton { background-color: #f8f9fa; border: none; border-radius: 12px; font-size: 20px; } QPushButton:hover { background-color: #e8ecf1; }")
        self.btnMessages.setObjectName("btnMessages")
        self.gridLayout_2.addWidget(self.btnMessages, 0, 6, 1, 1)
        self.mainContentLayout.addWidget(self.topBarFrame)
        self.contentScrollArea = QtWidgets.QScrollArea(parent=self.mainContentWidget)
        self.contentScrollArea.setStyleSheet("background-color: #f5f7fa; border: none;")
        self.contentScrollArea.setWidgetResizable(True)
        self.contentScrollArea.setObjectName("contentScrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 900, 745))
        self.scrollContent.setStyleSheet("background-color: #f5f7fa;")
        self.scrollContent.setObjectName("scrollContent")
        self.scrollContentLayout = QtWidgets.QVBoxLayout(self.scrollContent)
        self.scrollContentLayout.setContentsMargins(40, 38, 40, 38)
        self.scrollContentLayout.setSpacing(32)
        self.scrollContentLayout.setObjectName("scrollContentLayout")
        self.frame = QtWidgets.QFrame(parent=self.scrollContent)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0Profile = QtWidgets.QWidget()
        self.page0Profile.setObjectName("page0Profile")
        self.stackedWidget.addWidget(self.page0Profile)
        self.page1AllStudents = QtWidgets.QWidget()
        self.page1AllStudents.setObjectName("page1AllStudents")
        self.stackedWidget.addWidget(self.page1AllStudents)
        self.page2PendingRequests = QtWidgets.QWidget()
        self.page2PendingRequests.setObjectName("page2PendingRequests")
        self.stackedWidget.addWidget(self.page2PendingRequests)
        self.page3ManageFaculty = QtWidgets.QWidget()
        self.page3ManageFaculty.setObjectName("page3ManageFaculty")
        self.stackedWidget.addWidget(self.page3ManageFaculty)
        self.page4ManageCourses = QtWidgets.QWidget()
        self.page4ManageCourses.setObjectName("page4ManageCourses")
        self.stackedWidget.addWidget(self.page4ManageCourses)
        self.page5ManageSections = QtWidgets.QWidget()
        self.page5ManageSections.setObjectName("page5ManageSections")
        self.stackedWidget.addWidget(self.page5ManageSections)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.scrollContentLayout.addWidget(self.frame)
        self.contentScrollArea.setWidget(self.scrollContent)
        self.mainContentLayout.addWidget(self.contentScrollArea)
        self.mainHorizontalLayout.addWidget(self.mainContentWidget)
        AdminDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminDashboard)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(AdminDashboard)

    def retranslateUi(self, AdminDashboard):
        _translate = QtCore.QCoreApplication.translate
        AdminDashboard.setWindowTitle(_translate("AdminDashboard", "Admin Dashboard - ECE Registration System"))
        self.logoIconLabel.setText(_translate("AdminDashboard", "⚙️"))
        self.logoTitleLabel.setText(_translate("AdminDashboard", "Admin Panel"))
        self.logoSubtitleLabel.setText(_translate("AdminDashboard", "ECE Registration System"))
        self.labelAdminName.setText(_translate("AdminDashboard", "Admin User"))
        self.adminRole.setText(_translate("AdminDashboard", "Administrator"))
        self.adminStatus.setText(_translate("AdminDashboard", "🟢 Online"))
        self.avatarLabel.setText(_translate("AdminDashboard", "AD"))
        self.dashboardSectionLabel.setText(_translate("AdminDashboard", "DASHBOARD"))
        self.buttonProfile.setText(_translate("AdminDashboard", "📊  Profile"))
        self.userMgmtLabel.setText(_translate("AdminDashboard", "USER MANAGEMENT"))
        self.buttonAllStudents.setText(_translate("AdminDashboard", "👥  All Students (247)"))
        self.buttonApproveStudents.setText(_translate("AdminDashboard", "⏳  Pending Requests (12)"))
        self.buttonManageFaculty.setText(_translate("AdminDashboard", "👨‍🏫  Manage Faculty -WIP-"))
        self.courseMgmtLabel.setText(_translate("AdminDashboard", "COURSE MANAGEMENT"))
        self.buttonManageCourses.setText(_translate("AdminDashboard", "📚  Manage Courses (32)"))
        self.buttonManageSections.setText(_translate("AdminDashboard", "✏️  Manage Sections"))
        self.buttonLogout.setText(_translate("AdminDashboard", "🚪  Logout"))
        self.pageTitleLabel.setText(_translate("AdminDashboard", "Dashboard Overview"))
        self.breadcrumbLabel.setText(_translate("AdminDashboard", "🏠 Home • Dashboard"))
        self.btnSettings.setText(_translate("AdminDashboard", "⚙️"))
        self.btnNotifications.setText(_translate("AdminDashboard", "🔔"))
        self.btnMessages.setText(_translate("AdminDashboard", "💬"))
