# Form implementation generated from reading ui file 'register_courses_stackedwidget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterCoursesStackedWidget(object):
    def setupUi(self, RegisterCoursesStackedWidget):
        RegisterCoursesStackedWidget.setObjectName("RegisterCoursesStackedWidget")
        RegisterCoursesStackedWidget.resize(1200, 858)
        RegisterCoursesStackedWidget.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(RegisterCoursesStackedWidget)
        self.mainLayout.setContentsMargins(40, 40, 40, 20)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=RegisterCoursesStackedWidget)
        self.stackedWidget.setStyleSheet("background: transparent")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.mainLayout.addWidget(self.stackedWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem)

        self.retranslateUi(RegisterCoursesStackedWidget)
        QtCore.QMetaObject.connectSlotsByName(RegisterCoursesStackedWidget)

    def retranslateUi(self, RegisterCoursesStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        RegisterCoursesStackedWidget.setWindowTitle(_translate("RegisterCoursesStackedWidget", "Course"))
